import { Inter } from "next/font/google";
import Link from "next/link";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className={styles.nav}>
          <Link href="/">Logo</Link>
          <Link href="/newProduct">Add New Product</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
